version: '1'

services:
  postgres:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DATABASE: crm
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - /var/lib/postgresql
