version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: crm
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /var/lib/mysql
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: crm-app
  #   command: npm run dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/home/app
  #   environment:
  #     PORT: 8000
  #   depends_on:
  #     - db
