name: Lint

on:
	# Trigger the workflow on push or pull request
  push:
    branches:
      - master
			- develop

  # Replace pull_request with pull_request_target if you
  # plan to use this action with forks, see the Limitations section
  pull_request:
    branches:
      - master
			- develop

# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: write

jobs:
	run-linters:
		name: Run Linters
		runs-on: ubuntu-latest

		steps:
			- name: Cancel Previous runs
				uses: styfle/cancel-workflow-action@0.9.1
				with:
					access_token: ${{ github.token }}

			- name: Checkout Git Repository
				uses: actions/checkout@v2
				with:
					fetch-depth: 0
					persist-credentials: false

			- uses: amannn/action-semantic-pull-request@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setuping Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Installing dependencies
        run: npm i --legacy-peer-deps

      - name: Unit Tests
        run: npm run test

      - name: Test Lint
        run: npm run lint
